USE [PA_Feinkost]
GO

/****** Object:  Table [dbo].[tb_Kategorie]    Script Date: 22.11.2022 22:23:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tb_Kategorie](
	[KatID] [int] IDENTITY(1,1) NOT NULL,
	[KatName] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_tb_Kategorie] PRIMARY KEY CLUSTERED 
(
	[KatID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


