USE master
GO

CREATE DATABASE [PA_Feinkost]
 CONTAINMENT = NONE
 ON  PRIMARY 
(	NAME = N'PA_Feinkost', 
	FILENAME = N'C:\SQL_Projektarbeit\Datenbank\PA_Feinkost.mdf' , 
	SIZE = 8192KB , 
	FILEGROWTH = 10%
)
 LOG ON 
(	NAME = N'PA_Feinkost_log', 
	FILENAME = N'C:\SQL_Projektarbeit\Datenbank\PA_Feinkost.ldf' , 
	SIZE = 8192KB , 
	FILEGROWTH = 10%
)

GO
ALTER DATABASE [PA_Feinkost] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [PA_Feinkost] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PA_Feinkost] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PA_Feinkost] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PA_Feinkost] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PA_Feinkost] SET ARITHABORT OFF 
GO
ALTER DATABASE [PA_Feinkost] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PA_Feinkost] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PA_Feinkost] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [PA_Feinkost] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PA_Feinkost] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PA_Feinkost] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PA_Feinkost] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PA_Feinkost] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PA_Feinkost] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PA_Feinkost] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PA_Feinkost] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PA_Feinkost] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PA_Feinkost] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PA_Feinkost] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PA_Feinkost] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PA_Feinkost] SET  READ_WRITE 
GO
ALTER DATABASE [PA_Feinkost] SET RECOVERY FULL 
GO
ALTER DATABASE [PA_Feinkost] SET  MULTI_USER 
GO
ALTER DATABASE [PA_Feinkost] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PA_Feinkost] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PA_Feinkost] SET DELAYED_DURABILITY = DISABLED 
GO
USE [PA_Feinkost]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [PA_Feinkost]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [PA_Feinkost] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
